"use client"
import { motion } from "framer-motion"
import Link from "next/link"
import BottomHotbar from "@/components/bottom-hotbar"

export default function AboutPage(){
 const principles=[["Build our own things","Xeno Tech is focused on projects it owns and develops rather than client development."],["Experiment in public","Operating systems, languages, tools, and unusual prototypes are allowed to be experiments before they become products."],["Keep projects distinct","Abora, Pippin, Vanta, games, and developer tools can share an ecosystem without being forced into one stack."],["Community matters","Xeno's interactive roots still shape how projects are shared, tested, and built around the people using them."]]
 return <main className="min-h-screen bg-[#030811] text-white pb-32"><section className="px-6 pt-28 pb-24 bg-[radial-gradient(circle_at_50%_0%,rgba(37,99,235,.28),transparent_38%)]"><div className="max-w-6xl mx-auto"><Link href="/" className="text-blue-300/70">← Home</Link><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mt-20 max-w-4xl"><p className="text-sm uppercase tracking-[.28em] text-blue-300/60">About</p><h1 className="mt-4 text-6xl md:text-8xl font-light tracking-[-.05em]">Xeno Tech</h1><p className="mt-7 text-xl md:text-2xl text-slate-300 leading-relaxed">An independent home for systems software, developer tools, programming-language work, and interactive projects.</p></motion.div></div></section>
 <section className="px-6 py-20 bg-[#f7fbff] text-slate-950"><div className="max-w-6xl mx-auto grid lg:grid-cols-[.8fr_1.2fr] gap-12"><div><p className="text-sm uppercase tracking-[.25em] text-blue-600">Direction</p><h2 className="mt-3 text-4xl font-light">Small team.<br/>Wide range.</h2></div><p className="text-lg text-slate-600 leading-8">Xeno started around interactive projects and grew into a broader technology umbrella. Today the work ranges from Abora OS and Pippin to Vanta, LuminaIDE, TinyPM, desktop experiments, and games. The goal is not to look like a giant studio—it is to give independent projects room to become real, useful things.</p></div></section>
 <section className="px-6 py-24"><div className="max-w-6xl mx-auto"><p className="text-sm uppercase tracking-[.25em] text-blue-300/60">People</p><div className="mt-8 grid md:grid-cols-2 gap-5"><div className="rounded-[2rem] border border-blue-200/15 bg-white/[.04] p-8"><h3 className="text-3xl">Animated</h3><p className="mt-2 text-blue-300">Founder & Chief Architect</p><p className="mt-5 text-slate-400 leading-relaxed">Leads Xeno Tech and the architecture and direction of projects including Abora, Pippin, Vanta, and other software experiments.</p></div><div className="rounded-[2rem] border border-blue-200/15 bg-white/[.04] p-8"><h3 className="text-3xl">Anemunt</h3><p className="mt-2 text-blue-300">Collaborator · Tareno Labs</p><p className="mt-5 text-slate-400 leading-relaxed">Leads Tareno Labs and Modularity, collaborating across parts of the wider Xeno ecosystem.</p></div></div></div></section>
 <section className="px-6 pb-24"><div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-4">{principles.map(([a,b])=><div key={a} className="rounded-[1.75rem] border border-blue-200/10 p-7"><h3 className="text-2xl">{a}</h3><p className="mt-3 text-slate-400 leading-relaxed">{b}</p></div>)}</div></section><BottomHotbar/></main>
}
